### ISSUE TITLE
不兼容的类型: 无法推断类型变量 T,U,R,T,R

### ISSUE THREAD

**Issue by x1957** [weidagang/fava#2]
Error:(167, 61) java: 不兼容的类型: 无法推断类型变量 T,U,R,T,R
    (参数不匹配; 方法引用无效
      不兼容的类型: fava.promise.Promise<fava.PromiseTest.HttpPromise>无法转换为fava.promise.Promise<fava.promise.Promise<java.lang.String>>)

jdk 1.8.0_45

**Comment by weidagang** [comment]
Which file and line? It works here with Oracle JDK 8. Do you use OpenJDK or Oracle JDK?

**Comment by x1957** [comment]
PromiseTest.java line 167
Oracle JDK8

There are some warning, 

```
Warning:(59, 12) java: '_' 用作标识符
  (Java SE 8 之后的发行版中可能不支持使用 '_' 作为标识符)
```
